<?php
/**
 * Magentweet : Twitter Widget for Magento
 * by
 * Agence Dn'D - Creation site e-Commerce Magento - http://www.dnd.fr/magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * Available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Widget
 * @package    Dnd_Magentweet
 * @copyright  Copyright (c) 2010 Agence Dn'D (http://www.dnd.fr)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div id="magentweet" class="block block-magentweet <?php echo $this->getClasses(); ?>">
	<div class="block-title">
		<strong><?php echo $this->getTitle(); ?></strong>
	</div>
	<div class="block-content">
		<?php $search = $this->getSearch(); ?>
		<?php $results = $search->getResults(); ?>
		<?php if(is_array($results)): ?>
		<ul>
			<?php $i=0; ?>
			<?php  foreach($results as $result) : ?>
   			<li <?php if($i%2==0){ echo "class='odd'"; }else{ echo "class='even'"; } ?>>
   		 <img width="48px" height="48px" src="<?php echo $result['img']; ?>" />
   			<div><?php echo $result['content']; ?></div>
   				<?php $i++; ?>
   			</li>
			<?php endforeach; ?>
		</ul>
		<?php else: ?>
		<?php echo $this->__($results); ?>
		<?php endif; ?>
	</div>
</div>
