<?php
/**
 * Magentweet : Twitter Widget for Magento
 * by
 * Agence Dn'D - Création site e-Commerce Magento - http://www.dnd.fr/magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * Available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Widget
 * @package    Dnd_Magentweet
 * @copyright  Copyright (c) 2010 Agence Dn'D (http://www.dnd.fr)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div id="magentweet" class="block block-magentweet <?php echo $this->getClasses(); ?>">
	<div class="block-title">
		<strong><?php echo $this->getTitle(); ?></strong>
	</div>
	<div class="block-content">
		<?php $user = $this->getUser(); ?>
		
		<?php if($this->ifShowUserHeader()): ?>
			<a target="_blank" href="<?php echo $user->getUrl(); ?>"><img src="<?php echo $user->getImgUrl(); ?>" /></a>
			<strong><?php echo $user->getName(); ?><br/></strong>
			<?php echo $this->__('Followers') ?> : <?php echo $user->getFollowers(); ?>
			<?php echo $this->__('Following') ?> : <?php echo $user->getFollowing(); ?>
			<div class="clearer"></div>
		<?php endif; ?>
		
		<?php $statuses = $user->getStatuses(); ?>
		<ul>
			<?php $i=0; ?>
			<?php  foreach($statuses as $status) : ?>
   			<li <?php if($i%2==0){ echo "class='odd'"; }else{ echo "class='even'"; } ?>>
   				<?php echo $status; ?>
   				<?php $i++; ?>
   			</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>